# Generated by Django 3.2.22 on 2023-10-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('featured_image', models.ImageField(default='placeholder.jpg', upload_to='workout_images/')),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='signed_up_for', to=settings.AUTH_USER_MODEL)),
                ('session_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
