# Generated by Django 3.2.22 on 2023-11-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_workoutsession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
