# Generated by Django 3.2.22 on 2023-11-27 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signup', '0003_auto_20231104_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='content',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='session_creator',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='slug',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='available_spots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='instructor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.workoutsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
