# Generated by Django 3.2.22 on 2023-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20231127_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='available_spots',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
