# Generated by Django 3.2.22 on 2023-11-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20231127_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
    ]
