# Generated by Django 3.2.22 on 2023-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20231127_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='content',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='session_creator',
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='instructor_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
