# Generated by Django 3.2.22 on 2023-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_workoutsession_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session',
        ),
        migrations.AddField(
            model_name='booking',
            name='session_day',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_instructor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_title',
            field=models.CharField(default='WOD', max_length=200),
        ),
    ]
