# Generated by Django 3.2.22 on 2023-11-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_auto_20231128_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_instructor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_title',
        ),
        migrations.AddField(
            model_name='booking',
            name='workout_session',
            field=models.ForeignKey(choices=[(21, 'WOD - Monday at 08:00:00'), (22, 'Endurance WOD - Monday at 11:30:00'), (23, 'WOD - Monday at 15:00:00'), (24, 'Basic WOD - Monday at 17:00:00'), (25, 'WOD - Tuesday at 06:00:00'), (26, 'Endurance WOD - Tuesday at 11:00:00'), (27, 'WOD - Tuesday at 15:00:00'), (28, 'Basic WOD - Tuesday at 18:00:00'), (29, 'WOD - Wednesday at 08:00:00'), (30, 'Endurance WOD - Wednesday at 11:30:00'), (31, 'Basic WOD - Wednesday at 15:00:00'), (32, 'WOD - Wednesday at 17:00:00'), (33, 'WOD - Thursday at 07:00:00'), (34, 'Basic WOD - Thursday at 10:30:00'), (35, 'Endurance WOD - Thursday at 17:00:00'), (36, 'Endurance WOD - Friday at 06:00:00'), (37, 'WOD - Friday at 09:30:00'), (38, 'Basic WOD - Friday at 16:00:00'), (39, 'WOD - Friday at 18:00:00'), (40, 'WOD - Saturday at 08:00:00'), (41, 'WOD - Saturday at 10:30:00'), (42, 'WOD - Saturday at 12:30:00'), (43, 'WOD - Saturday at 17:00:00'), (44, 'WOD - Sunday at 09:00:00'), (45, 'WOD - Sunday at 11:30:00'), (46, 'Endurance WOD - Sunday at 15:00:00'), (47, 'WOD - Sunday at 17:00:00'), (48, 'WOD - Thursday at 15:00:00')], default=1, on_delete=django.db.models.deletion.CASCADE, to='signup.workoutsession'),
        ),
    ]
