# Generated by Django 3.2.22 on 2023-11-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20231129_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.workoutsession'),
        ),
    ]
