# Generated by Django 3.2.22 on 2023-12-12 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_remove_workoutsession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='available_spots',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='booked_spots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
